apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
      - name: post
        image: aghaali1/post:latest
        ports:
        - containerPort: 8080
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumes:
  - name: mongo-data
    emptyDir: {}
